[package]
name = "specs-game"
version = "0.1.0"
authors = ["Caleb Boylan <calebboylan@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
ggez = '0.5'

[dependencies.specs]
version = '0.16'
features = ['shred-derive']
