[package]
name = "specs-game"
version = "0.1.0"
authors = ["Caleb Boylan <calebboylan@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
tiled = "0.9"
glutin = "0.24"
gl = "0.14"
image = "0.20"

[dependencies.specs]
version = '0.16'
features = ['shred-derive']
